version: 3.8
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api/:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/root
      - /root/node_modules
    ports:
      - 8080:3000
    command: npm run dev
  express-api-ts-mariadb:
    image: mariadb:10.6
    container_name: express-api-ts-mariadb
    volumes:
      - ._mysql_data_dir/:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    restart: always
