version: '3.8'
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api/:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000']
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/root
      - /root/node_modules
    ports:
      - 8080:3000
      - 24678:24678
    command: npm run dev
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    volumes:
      - ._mysql_data_dir/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_DATABASE
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 15s
      retries: 20
