version: "3.8"
services:
  api:
    build: ./api
    ports:
      - 3000:3000
    volumes:
      - ./api/:/app
      - /app/node_modules
    environment:
      NODE_ENV: "development"
    command: npm run dev

  frontend:
    build: ./frontend
    volumes: 
      - ./frontend/:/root
      - /root/node_modules
    ports:
      - '8080:3000'
    command: npm run dev
